
export const UPDATE_CODE = 'UPDATE_CODE'

export const TOGGLE_SOURCEMAP = 'TOGGLE_SOURCEMAP'

export const OPTIMIZE = 'OPTIMIZE'
export const OPTIMIZE_PENDING = 'OPTIMIZE_PENDING'
export const OPTIMIZE_FULFILLED = 'OPTIMIZE_FULFILLED'
export const OPTIMIZE_REJECTED = 'OPTIMIZE_REJECTED'
